version: "2.1"
volumes:
    couchdb-data:
services:
    database:
        image: couchdb:latest
        volumes: 
            - 'couchdb-data:/opt/couchdb/data'
        ports: 
            - 5984:5984
            - 80:5984
        environment: 
            COUCHDB_USER: admin
            COUCHDB_PASSWORD: admin
            COUCHDB_UPSTREAM_DBNAME: iotdata 
            COUCHDB_DOWNSTREAM_DBNAME: globalconfig 
        networks:
            default:
                aliases:
                    - database.local
    bootstrap:
        build:
            context: ./bootstrap
            dockerfile: Dockerfile.template
        environment: 
            COUCHDB_USER: admin
            COUCHDB_PASSWORD: admin
            COUCHDB_UPSTREAM_DBNAME: iotdata 
            COUCHDB_DOWNSTREAM_DBNAME: globalconfig 
        depends_on: 
            - database
        restart: "no"

    replacer:
        build: 
            context: ./replacer
            dockerfile: Dockerfile.template
        ports: 
            - 90:80
        environment: 
            COUCHDB_USER: admin
            COUCHDB_PASSWORD: admin
            COUCHDB_UPSTREAM_DBNAME: iotdata 
            COUCHDB_DOWNSTREAM_DBNAME: globalconfig 
        depends_on: 
                - bootstrap
